######################################################################
# Automatically generated by qmake (3.0) ?? 6? 12 17:12:41 2016
######################################################################

TEMPLATE = app
TARGET = vcard
INCLUDEPATH += .

# Input
HEADERS += libvcard_global.h vcard.h vcardparam.h vcardproperty.h
SOURCES += main.cpp vcard.cpp vcardparam.cpp vcardproperty.cpp
